POST http://localhost:3000/search/update 

###
POST http://localhost:3000/search/update 
Content-Type: application/json

{
    "indexName":20
}

###
POST http://localhost:3000/api/embed 
Content-Type: application/json

{
    "indexName":20,
    "question": "What is the status of my order?",
    "answer": "Your order is in transit. It will be delivered by 5pm today."
}

###
POST http://localhost:3000/api/json
Content-Type: application/json

[{
"indexName":21,
"question": "Where is my order?",
"answer": "Your food is on the way. It will be delivered by 5pm today."
},{
"indexName":20,
"question": "Where is job?",
"answer": "your job is waiting for you."
},{
"indexName":20,
"question": "Where is my food?",
"answer": "Your food is in the kitchen."
},{
"indexName":20,
"question": "Where is my Key?",
"answer": "Your food is in the bedroom."
}]


###
DELETE http://localhost:3000/api/delete
Content-Type: application/json

{
    "indexName":20,
    "question":"Where is my Key?"
}

###
GET http://localhost:3000/api/match?sentence=hello%3F&indexName=20&neighbors=3
Content-Type: application/json

# {
#     "indexName":20,
#     "sentence":"Where is my Key?"
# }