const fillerMap = new Map([
    [1, 'Gotcha'],
    [2, 'Yah gotcha'],
    [3, 'Ok gotcha'],
    [4, 'Wow'],
    [5, 'Ok yah'],
    [6, 'Totally'],
    [7, 'Yah totally'],
    [8, 'Yeah'],
    [9, 'Interesting'],
    [10, 'Definitely'],
    [11, 'For sure'],
    [12, 'Uh-huh'],
    [13, 'Mhmm'],
    [14, 'Gotcha'],
    [15, 'Ok gotcha'],
    [16, 'Wow'],
    [17, 'Ok yah'],
    [18, 'Yah umm'],
    [19, 'Ummm yah'],
    [20, 'Yeah'],
    [21, 'Okay'],
    [22, 'Yah umm'],
    [23, 'Ummm'],
    [24, 'Ummm yah'],
    [25, 'Yeah'],
    [26, 'Uh-huh'],
    [27, 'Mhmm'],
    [28, 'Yah umm'],
    [29, 'Ummm'],
    [30, 'Ummm yah'],
    [31, 'Yeah'],
    [32, 'Uh-huh'],
    [33, 'Mhmm'],
    [34, 'Yah umm'],
    [35, 'Ummm'],
    [36, 'Ummm yah'],
    [37, 'Yeah'],
    [38, 'Gotcha'],
    [39, 'Yah gotcha'],
    [40, 'Ok gotcha'],
    [41, 'Ok yah'],
    [42, 'Yah totally'],
    [43, 'Yeah'],
    [44, 'Uh-huh'],
    [45, 'Mhmm'],
    [46, 'Yah umm'],
    [47, 'Ummm'],
]);

export default fillerMap;
